### ISSUE TITLE
Update to python 3.9

### ISSUE THREAD

**Issue by zaro0508** [CloudSnorkel/CloudWatch2S3#14]
We tried to deploy however AWS says it no longer supports python3.6.  The lambdas in this solution needs to be updated to python3.9

We deployed from the AWS serverless repository:
```
Resources:
  CloudWatch2S3:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:859319237877:applications/CloudWatch2S3
        SemanticVersion: 1.0.4
```

Error from AWS:
```
Resource handler returned message: "The runtime parameter of python3.6 is no longer
supported for creating or updating AWS Lambda functions. We recommend you use the
new runtime (python3.9) while creating or updating functions. 
```
